services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      AUTO_SERVER_URL: 0
      SERVER_URL: http://192.168.1.41:11470/	
      #IPADDRESS: 192.168.1.41 # Setup your ip address here
    ports:
      - "8080:8080"
    volumes:
      - "./stremio-data:/root/.stremio-server"
