services:
  stremio:
    image: tsaridas/stremio-docker:latest
    restart: unless-stopped
    environment:
      NO_CORS: 1
      AUTO_SERVER_URL: 1	
      IPADDRESS: 192.168.1.41 # Setup your ip address here
    ports:
      - "8181:8181"
    volumes:
      - "./stremio-data:/root/.stremio-server"
